services:
  pytorch:
    build:
      context: .
      dockerfile: Dockerfile
    shm_size: 40g
    privileged: true
    ipc: host
    runtime: nvidia
    gpus: all
    ports:
      - 6008:6008
    environment:
      - CUDA_VISIBLE_DEVICES=3
      - PUID=1000
      - PGID=1000
      - TORCH_DISTRIBUTED_DEBUG=DETAIL
      - HF_HOME=/app/cache/huggingface
    volumes:
      - /mnt/nas/TAmob/preprocessing_scripts/targeted_review:/app
      - /mnt/nas/TAmob/cache:/app/cache
      # /app/data's structure should be as follows:
      # └── train/
      # │    ├── images/      Contains image files (.jpg, .jpeg, .png)
      # │    └── labels/      Contains YOLO format label files (.txt)
      # app/data is the directory that should contain the training data (usually ends with _labeled)
      # This is the usual output directory structure of the autolabelling / autodistillation model
      - /mnt/nas/TAmob/old_data/recent_data:/app/data
      - /mnt/nas/TAmob/preprocessing_scripts/targeted_review/class_map.json:/app/class_map.json
      - /mnt/nas/TAmob/old_data/targeted_review_outputs/pipeline_output6:/app/output_data 
    tmpfs:
      - /tmp
    command: >
      python3 /app/pipeline.py
      --input_and_label_dir "/app/data"
      --class_map_json "/app/class_map.json"
      --output_folder "/app/output_data"
      --batch_size 8
      --subset Train
#     --diversified_csvs "/app/modelA_preds.csv" "/app/modelB_preds.csv"